/**
 * Regenerate the table of contents in README.md from its headings,
 * so it can't drift from the actual structure.
 * Run automatically at the end of `.github/workflows/build.sh`,
 * right after generate-tables.js.
 */

import { readReadme, replaceMarkedSection, writeReadme } from './readme.js';

// same slug rules github uses: strip punctuation, spaces to hyphens,
// duplicates get a -1, -2, ... suffix
const slugCounts = {};
const slugify = heading => {
	const base = heading
		.toLowerCase()
		.replace(/<[^>]+>/g, '')
		.replace(/[^\p{L}\p{N} _-]/gu, '')
		.trim()
		.replace(/ /g, '-');
	const count = slugCounts[base] ?? 0;
	slugCounts[base] = count + 1;
	return count === 0 ? base : `${base}-${count}`;
};

const stripInlineMd = heading => heading.replace(/`([^`]*)`/g, '$1').replace(/\[([^\]]*)\]\([^)]*\)/g, '$1');

const buildToc = readme => {
	const lines = [];
	let inCodeBlock = false;
	let inTocSection = false;

	for (const line of readme.split('\n')) {
		if (/^\s*```/.test(line)) {
			inCodeBlock = !inCodeBlock;
			continue;
		}
		if (inCodeBlock)
			continue;
		if (line.includes('AUTOGENERATED:TOC:START'))
			inTocSection = true;
		if (line.includes('AUTOGENERATED:TOC:END'))
			inTocSection = false;

		const match = line.match(/^(#{2,3}) (.+?)\s*$/);
		if (!match || inTocSection)
			continue;
		const [, hashes, rawHeading] = match;
		const heading = stripInlineMd(rawHeading);
		const indent = '\t'.repeat(hashes.length - 2);
		lines.push(`${indent}* [${heading}](#${slugify(rawHeading)})`);
	}

	return lines.join('\n');
};

const readme = readReadme();
writeReadme(replaceMarkedSection(readme, 'TOC', buildToc(readme)));
