/**
 * Shared README plumbing for the scripts that keep parts of it generated.
 * Each of those parts is delimited by a pair of
 * `<!-- AUTOGENERATED:<MARKER>:START -->` / `:END` comments, so the markers
 * (and the "run ... to regenerate" hint they carry) survive a rewrite.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const readmePath = path.join(path.dirname(path.dirname(fileURLToPath(import.meta.url))), 'README.md');

export const readReadme = () => fs.readFileSync(readmePath, 'utf8');

export const writeReadme = readme => fs.writeFileSync(readmePath, readme);

export const replaceMarkedSection = (readme, marker, body) => {
	const re = new RegExp(`(<!-- AUTOGENERATED:${marker}:START[^\\n]*-->)[\\s\\S]*?(<!-- AUTOGENERATED:${marker}:END -->)`);
	if (!re.test(readme))
		throw new Error(`Could not find "AUTOGENERATED:${marker}" markers in README.md`);
	return readme.replace(re, `$1\n${body}\n$2`);
};
